import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Homepage } from '@/components/Homepage';
import { Benefits } from '@/components/Benefits';
import { Faq } from '@/components/Faq';
import Inievent, { EventDetails } from '@/components/Inievent';

const event1ImageSrc = '/assets/event1.jpeg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Example events data
const exampleEvents: EventDetails[] = [
  {
    id: 1,
    image: event1ImageSrc, //still not showing
    title: 'Event 1',
    date: '2023-01-01',
    location: 'Jakarta',
    cost: 'RP.100.0000',
  },
  // Add more events as needed
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="main-content">
          <Homepage />

          {children}
          <div />
          <div>
            <Benefits />
          </div>
          <div>
            <Faq />
          </div>
          <div>
            <Footer />
          </div>
          {/* <div>
            <Inievent events={exampleEvents} />
          </div> */}
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { Header } from '@/components/Header';
// import { Footer } from '@/components/Footer';
// import { Homepage } from '@/components/Homepage';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         <Homepage />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
