import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Homepage } from '@/components/Homepage';
import { Benefits } from '@/components/Benefits';
import { Faq } from '@/components/Faq';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="main-content">
          <Homepage />

          {children}
          <div />
          <div>
            <Benefits />
          </div>
          <div>
            <Faq />
          </div>
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { Header } from '@/components/Header';
// import { Footer } from '@/components/Footer';
// import { Homepage } from '@/components/Homepage';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         <Homepage />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
