import { Categories } from '@/components/Categories';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import React from 'react';

const LoginPage = () => {
  return (
    <div>
      <Header />
      <Categories />
      <Footer />
    </div>
  );
};

export default LoginPage;

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { Header } from '@/components/Header';
// import { Footer } from '@/components/Footer';
// import { Homepage } from '@/components/Homepage';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         <div className="main-content">
//           <Homepage />

//           {children}
//           <div />
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }
